apiVersion: apps/v1
kind: Deployment
metadata:
  name: sse-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sse-demo
  template:
    metadata:
      labels:
        app: sse-demo
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: sse-demo
          image: ghcr.io/m84633/sse-demo:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: sse-demo-config
            - secretRef:
                name: sse-demo-secret
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
