---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: sse-demo
spec:
  encryptedData:
    .dockerconfigjson: AgDLziY5xvqkip6JTIixNhIeM3fhLLI457PaHWKoCb6lJGnh8UEQQIQictd5aRDzgZnLTyID2HZDgSTEYvadexV/+CQ89YpmdkteAeXmUjz+rTqYYbZkEUDzkPTCxlGCfWUFl1Od0/tfMevttg0u2lwZa21T4iGIKQxG28U+e8y/+xYYREMM//oMX7szEv+NsOBDGvF+m1+k3VPrceOTRawNxNU7bW7OdXSwQGt6EINeIdKbN6XeNepp9F4/8x2bUL8+FGuy8A5NYai0qJ/9tJ0CmsfwwbZb5Do0FghMzcWjkylnRMN0NqrvJpso6JI1t8d57gf3g77ZT0CtUySt6o781uKxbZhHS12AH+8ptuatG7RtpEQ7Atu0jmiCNY8XEkwEoYE0BIG+j1mpniMsUBdC9Y+uKHOF7PGmE6pzMSdpTdReIx87CjUrLDFYq8yLyEnmJpGiHH9NaxNsmzyWOG4n9y62ipusv3qFNEA3bui6ompLMh9I9LAz7eiZ3U6i2VIhOxwoUwvrZskSpVkejp3bJi46RV0MGOy0CR/1qbwToVSSrO7KBUUAqhSLmdTD9PZbq0imNhc/odJUREUu9bPFFTmRu0e9mnpIiBmMZI7UPxFPNS8Ht281wfL0/RHmSv2DVd1W7EXAV7csWZ0+5fBEQj9VRiSgkQ6sDBVVXv3s6t/DzFxW0pnMScBDP+RNH/aXYvqIJarI7GrXnEJKpGhGqej51ZixbhzF+hiQkvLoIBluWIxD4cjp+n0okamOsd1t0c+SPT6lZY24fMqv2m6D//nQpvFFxLqFuL7x8yuzzJ2Ghd+rcnNaACq+Mx8UojaOMOg/XUWbjd3vFhewhO9N9wronKVhiNd2M2HxxsfDNQPI2IUaQtuBhcKQz5dW/jCqUHOXZVBSz3vU+XNLzKb05N80amsNVOgjc5Ca
  template:
    metadata:
      name: ghcr-credentials
      namespace: sse-demo
    type: kubernetes.io/dockerconfigjson
