---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: sse_demo
spec:
  encryptedData:
    .dockerconfigjson: AgCCKUyYDACnfPAsGo7/xl8u9NBldTNwghCuTBKKUo1RWuL4Kw+TD2L+SiNuB6qG9BzsU4Coh3CaUwAIHAXxiwt+mWVMP7hIVi/FSI3MZjq2kjf4ThuCs5GU0s5EOpJzLIcnX333m/fjYdfLKdBY4+lyC5/pB5U35hJz6NjjU1FAIhkAa1ZqbFMnOwaz11MwOkiL93S40vXKeBoy44qNdhIH111/X4rli+zXn1ReKUh+Iut/Azx53UDi5V++Ni51gfVezXSNnX4LNYkAVBdlH6Wc6lnynC+PaENgzWugiIDGWowEFc29leTa1EEqv2CG31z4wEvDWRJ2oC1hN9XjvjMnQWQ0JAuP8pkjGyEzh11rfpKol9JjrQieeeY2xQ2MWZeJKFxDusKNbA1Lsu9ab1/+G1mnrkrBxfFXHucDQ4p4i77GDAUFgqiRMtV2ifY2XGozvTtxXAlW6tke+a0YwYpvWsGpsWQb/Jt9z59BNaf6mZhne5P+1qdvz1mLihaJgjHnqY2THoylN+I56p9sIWJWvU5XYMMYLARptaLoBsrqbCyp4cls3jTIhe0HZHOvKchdWEpTpn1CqDc5PcrwjsP1KtXMnl4r28WDt3DyOrxZSjiZOgobuasMcux7wAI+VUJUEnhLA4hsCyjr0p7izdFHSnTQJsNpsEI92zN0prpXJ5UGZm7s1NCTvvQ2JvBOVJGg2ksXyPUgheEU8VfxIdLN9ZWrCWf63U8wOHQNeulMbwlCPHUw1tHTRP2AkprjmniPZwGemb2rIvrcBnguuLtzG92c2DEOGQ5Y0jKqB3RJsZv7QipzWYk/ukycSnwaZdol2vZc2Hgf7jq3lH1idX/XYxl2i44JaSu9vqg4Nm9uPzxHXHDU+R8ihssDFFSBJfB2CMjFopKich+pTsg+2ggtx86uikcfhqFd9N0V
  template:
    metadata:
      name: ghcr-credentials
      namespace: sse_demo
    type: kubernetes.io/dockerconfigjson
