apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sse-demo
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealedsecret.yaml
  - ghcr-credentials.sealedsecret.yaml
configMapGenerator:
  - name: sse-demo-config
    envs:
      - config.env
generatorOptions:
  disableNameSuffixHash: false
images:
  - name: ghcr.io/m84633/sse-demo
    newTag: ec203a19c739b9abe84d2c34bca80fe2654f97b6
