apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sse-demo
resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingress.yaml
  - sealedsecret.yaml
  - ghcr-credentials.sealedsecret.yaml
configMapGenerator:
  - name: sse-demo-config
    envs:
      - config.env
generatorOptions:
  disableNameSuffixHash: false
images:
  - name: ghcr.io/m84633/sse-demo
    newTag: 30b98894c3564db8498cc4e90fec4ab7a018e2f8
