apiVersion: v1
kind: Service
metadata:
  name: sse-demo
  labels:
    app: sse-demo
spec:
  selector:
    app: sse-demo
  ports:
    - name: http
      port: 80
      targetPort: 8082
  type: ClusterIP
